### ISSUE TITLE
[error]  The Flysystem driver is missing. 

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-dc#136]
When i run make install the installation script returns the error in the title. There is a flysystem driver inside the composer file, so it should be there.
I follow the installation procedure for local. I don't do anything special, just follow the readme.

**Comment by DonRichards** [comment]
So it looks like the build process needs Fedora exposed to work. In some cases adding "**True**" to the `.env` file for fedora seems to have corrected the Flysystem issue. Just modify your file, then run `make pull` then `make up` and it should be fine.

**Comment by seniordev-ca** [comment]
@DonRichards , `EXPOSE_FEDORA=true` in `.env` file.
But still getting the same error. Do you have any idea?

I did run `make local`

![image](https://github.com/Islandora-Devops/isle-dc/assets/50069715/ed3dc193-b089-4a3d-ac82-e49490db9bc8)

**Comment by DonRichards** [comment]
Those are known messages and should be ignored. https://github.com/Islandora-Devops/islandora-starter-site#known-issues 
It's likely an issue with how the Islandora module installs. The tech call agrees it needs to be addressed so there isn't any further confusion. But thanks for pointing this one out. I'm only going to close this because it's a known issue and is documented.
