### ISSUE TITLE
"Extract Text from Image or PDF" not working

### ISSUE THREAD

**Issue by jasonhildebrand** [Islandora-Devops/isle-dc#163]
I installed a fresh instance of Islandora using isle-dc, but cannot get text extraction to work.  I'm new to Islandora (but familiar with Drupal 8 and docker).  I watched the Paged Content webinar from last year and checked the docs, so that's what I'm going on.

What I tried:
 * created a new repository item using Model "Digital Document".  Save.
 * Go to Media and use "Add Media", select "File".  Upload a PDF.  Check "Original File".  Save.
 * Check the Media tab.  It shows mime type "application/pdf" for the file I uploaded.  It generates a thumbnail.  However no "Extracted Text" derivative shows up.
 * Ran cron manually, in case this job is queued.  Still no Extracted Text derivative.
 * Checked under Structure -> Context.  Found a rule for "PDF Derivatives" which should have been triggered based on "Digital Document" and Media "Original File"
 * No clues in Reports -> Recent Log Messages
 * all containers are up according to `docker-compose ps`
 * my understanding is that hypercube is responsible for extracting text.  `docker-compose logs --tail=1000 hypercube` shows no new output when I upload media.  The last line is `hypercube_1   | [07-Jun-2021 20:25:47] NOTICE: ready to handle connections`.

I also tried creating Paged Content with a child of model Page and uploaded a JPG media file (containing some text).  According to the rules in Context, I expected the "Extract Text" action would be triggered in this scenario, but I saw no evidence.  No Edited Text derivative was created.

I would appreciate any clues to help get this working.

**Comment by terrywmc** [comment]
Same here, I installed the demo app with the default config, and uploaded a tiff file for testing. no extracted text was created.

Checked the ActiveMQ panel, there was no consumer connecting to the queue "islandora-connector-ocr" and "islandora-indexing-fcrepo-file-delete".  

For the ocr queue,  It was discovered that the reason was the incorrect karaf setting for the following. I updated the param to "10" to get the consumer back temporarily.
https://github.com/Islandora-Devops/isle-buildkit/blob/main/alpaca/rootfs/etc/confd/templates/ca.islandora.alpaca.connector.ocr.blueprint.xml.tmpl#L13

Another thing was that the jwt key syn for the hypercube image did not work and the PHP application prompted "Permission denied" at: /opt/keys/jwt/syn-settings.xml. So I disabled the jwt temporarily to get the orc work temporarily.

**Comment by kayakr** [comment]
@jasonhildebrand @terrywmc An issue re routing requests to hypercube was recently fixed, see https://github.com/Islandora-Devops/isle-buildkit/pull/152

**Comment by jasonhildebrand** [comment]
@kayakr Thanks for the heads-up.  Working on a different project right now but I will re-test when I am able.

**Comment by jasonhildebrand** [comment]
After bumping the version in my .env file to the latest version (1.0.0-alpha-10) and restarting (pulling) containers, I can confirm that the extracted text derivative is now being created as expected.

Thanks for all involved for tracking down and resolving this issue.
