### ISSUE TITLE
Toronto is still coming up as default timezone not UTC.

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#27]
Toronto is still coming up as default timezone not UTC for the newly created Drupal site when resetting admin password.

**Comment by g7morris** [comment]
@nikathone Some history from our [PR convo](https://github.com/Islandora-Devops/isle-dc/pull/6#issuecomment-614147612)

"The process for checking the timezone comes up when I run docker-compose -p islandora exec drupal drush uli, copy the drush uli generated login reset link and open the url in a new browser, change the password and then scroll down to see the timezone which is stuck on Toronto. I'll rebuild in a few moments and put a screenshot up."

**Comment by g7morris** [comment]
@nikathone Just an FYI that I see this error when I run `make` 

`[Warning] One or more build-args [PHP_DATE_TIMEZONE] were not consumed` 

Feels like these might be related no?

**Comment by nikathone** [comment]
@g7morris yes and no. The build args warning is because I didn't add `ARG PHP_DATE_TIMEZONE=UTC` in stage 3 inside the `drupal.Dockerfile`. 

The default timezone being Toronto is coming from Drupal config (see the `codebase/sync/system.date.yml` file) which might need to update. 
<img width="1021" alt="Screen Shot 2020-04-30 at 4 50 52 PM" src="https://user-images.githubusercontent.com/7364989/80758812-3dbabe00-8b04-11ea-9ddd-03d00f39636d.png">

Setting `ARG PHP_DATE_TIMEZONE=UTC` inside `drupal.Dockerfile` won't  fix this but it ensure that the default php date timezone is also UTC.

Let me know if I should go ahead and create a PR to update `drupal.Dockerfile` to include `ARG PHP_DATE_TIMEZONE=UTC` which will suppress the warning.
