### ISSUE TITLE
islandora_install_profile_demo missing

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Devops/isle-dc#318]
`docker-compose exec -T drupal with-contenv bash -lc "drush si -y islandora_install_profile_demo --account-pass password"`
is pointing to "islandora\islandora_install_profile_demo" This is pointing to the wrong location. 

It should point to https://github.com/Islandora-Devops/islandora_install_profile_demo 
This needs to be added to one of the repose that brings in this repo

**Comment by aOelschlager** [comment]
Sorry in advance for the wall of text. The name would need to be changed in the islandora install profile demo and islandora sandbox https://github.com/Islandora-Devops/islandora_install_profile_demo/blob/main/composer.json#L2
https://github.com/Islandora-Devops/islandora-sandbox/blob/main/composer.json#L82

I will add though that the url for that repo is pointing to the right github repository in islandora sandbox https://github.com/Islandora-Devops/islandora-sandbox/blob/main/composer.json#L18

The islandora name is also the same for islandora-sandbox, islandora_base_theme, and islandora_starter_theme repos https://github.com/Islandora-Devops/islandora-sandbox/blob/main/composer.json#L2
https://github.com/Islandora-Devops/islandora_base_theme/blob/main/composer.json#L2
https://github.com/Islandora-Devops/islandora_starter_theme/blob/main/composer.json#L2

Are these suppose to be named islandora-devops instead of islandora? 
According to composer's documentation it's the vendor's name and the project's name (vendor/project.) What would be considered the vendor? https://getcomposer.org/doc/04-schema.md#properties

If that's the correct vendor, there would need to be changes in 4 different repositories' composer.json file and islandora sandbox's composer.lock file for both the name of the package and the name in the require section for the other repositories with name changes that it references.

**Comment by noahwsmith** [comment]
I see - the name here is cosmetic - it could be anything. 

@aOelschlager got it exactly right. If we want to change this cosmetic name to be `islandora-devops/whatever` instead of `islandora/whatever` we'll need to change it in the various source repositories as well as change it in all the composer.json's that call for it.

I don't have a strong opinion on this. I think it's fine as-is, but maybe others disagree.

**Comment by DonRichards** [comment]
Thanks. I'll close
