### ISSUE TITLE
M1 Issues with utilities.sh

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Devops/isle-dc#323]
I’m seeing an irregularity that only happens on my M1 Mac but not on my Ubuntu machine. And I think it’s associated with utilities.sh file. Specifically when the `$(MAKE) drupal-database update-settings-php` is called. It changes the permissions of settings.php to 400 and doesn’t allow Flysystem to chmod it. This doesn’t happen on the other machine, and I assume it has something to do with the fact that Mac users might not translate to 1000 user ID. 

```shell
chmod 777 codebase/web/sites/default/settings.php
docker-compose exec -T drupal with-contenv bash -lc "for_all_sites update_settings_php"
...
In Filesystem.php line 203:
  Failed to chmod file "/var/www/drupal/web/sites/default/settings.php".
chown: /var/www/drupal/web/sites/default/settings.php: Permission denied
```

**Comment by noahwsmith** [comment]
This literally started for me yesterday, too! I think it coincided with me upgrading to v4.16.2

Did you do the Docker for Mac update recently?

**Comment by DonRichards** [comment]
Yeah, I have the same version.

**Comment by noahwsmith** [comment]
Looks like other projects are seeing similar things (e.g. https://github.com/itzg/docker-minecraft-server/discussions/1926) but this seems to be very much a corner case.

I rolled back to 4.16.1 by downloading and replacing my Docker application with the one available here https://docs.docker.com/desktop/release-notes/#4161 and that didn't solve the problem. Switching to gRPC Fuse instead of VirtioFS worked! ~~I was then able to switch back to VirtioFS and `make update-settings-php` works again on 4.16.1.~~ (I retested and this didn't work after `make clean` - it must have been stuck in gRPC Fuse 😞 

@DonRichards maybe you'll test ~~flipping filesharing back and forth~~ GRPC Fuse within 4.16.2 to see if that fixes this in the latest version ~~or if that's just what you have to do to get VirtioFS "reset" back to the previous working version~~?

I'll post a warning on Slack about this so others don't trip up on this.

**Comment by dheles** [comment]
Thanks for the warning. Do we happen to know if Intel macs are similarly affected?

**Comment by ysuarez** [comment]
@aOelschlager and I tried to add a warning on the Islandora docs about this issue for mac users, but the docs did not rebuild. We will look at the docs again next week.

**Comment by DonRichards** [comment]
Closing, no longer experiencing any issues.

**Comment by noahwsmith** [comment]
We're still seeing issues with `VirtioFS` in the "Pre-Nigel's Rebuild" era of containers. I haven't tested VirtioFS with the latest release candidate containers, but I can say that `gRPC FUSE` works in all versions of Docker For Mac for us.

**Comment by joecorall** [comment]
Can this issue be closed? Sounds like it is not an issue for modern isle-buildkit tags?

**Comment by noahwsmith** [comment]
Yes, I believe so
