### ISSUE TITLE
Some networks were defined but are not used by any service: external

### ISSUE THREAD

**Issue by nikathone** [Islandora-Devops/isle-dc#73]
When running:

```bash
docker-compose -p islandora down \
                --rmi local \
                --volumes \
                --remove-orphans
```
or
```bash
docker-compose -p islandora up --remove-orphans --detach
```

Is there any issue to removed unneeded settings from the main `docker-compose.yml`?

**Comment by g7morris** [comment]
@nikathone Are you referring to previous Traefik network settings (from MVP 1, 2a & 3) and container name lines in the docker-compose.yml when you mean "unneeded settings"?

I think we still had some issues with removing these lines when I was testing in MVP3, if I recall off hand the mariadb image didn't work properly as a result and some services could connect like Drupal but others like fcrepo couldn't unless they were all in the same network. 

I would ask perhaps that we also consult prior with @jefferya as to what we're trying to achieve with removing all of the Trafeik labels, container names etc? 

I'd like to loop him in on this too so we can make changes in the right areas. 

If those aren't the unneeded settings and I've missed the point, what are you recommending here @nikathone for moving forward?

**Comment by nikathone** [comment]
Under network in the docker compose there are two networks: external and internal. The `external` network isn't attached to any services.

The `internal` network isn't needed either. The services should be able to talk to each other through [default network](https://docs.docker.com/compose/networking/) and their service names.

**Comment by jefferya** [comment]
@g7morris : Isle 7 was configured to use and internal/external network , for example, [compose.production.yml#L172-L173](https://github.com/Islandora-Collaboration-Group/ISLE/blob/master/docker-compose.production.yml#L172-L173). Was there a particular Isle 7 use case? 

I personally don't have an applicable use case. I'm ok with the simplification assuming is no known use case. I wouldn't want to make the change from Isle 7 -> 8 harder for the user community. 

What is unknown to me. 
* Are users leveraging the [advance network features](https://docs.docker.com/engine/reference/commandline/network_create/) such as `--internal`- if yes, then defining the dual networks maybe necessary
- In Isle production environments, Kubernetes based, is there a need for the internal/external separation for securing certain containers from external access, e.g., db? For example, if a tool like Komposer is used to generate the Kubernetes deployments/services or Helm chart, does the tool need the internal/external network? <https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/>

**Comment by g7morris** [comment]
@jefferya Thanks for the update. 

Indeed the only use case we had for ISLE 7 was to use the internal / external functionality and networks to:

- allow an external network for wider public access e.g. a local laptop or in production only allowing ports 80 / 443 to be internet accessible.
- to not fully expose all services and ports publicly (e.g. mysql, fedora, solr) unless a sys-admin or developer needs to. 

Lastly the internal network as used by docker-compose is ideal in that docker-compose service names can be passed as values to configs or other services themselves for interaction. (I suspect that is more of a default docker-compose ability rather than traefik providing it outright)

I'd say that it sounds like we want to continue to protect a fair amount of services e.g. isle-fcrepo, activemq from being "public" to the internet. That we need to define and expose ports for admin dashboards e.g. activemq, fcrepo, solr etc is necessary exposure to a point for sys-admins, users etc via the docker-compose.yml file but all with the understanding that on a production system these ports would also be behind a firewall. 

I cannot answer anything with relation to Kubernetes as we've not tested using ISLE in that type of environment. 

For now in the interest of moving forward, it sounds like it would be okay to:

a) remove all container naming  lines from docker-compose.yml
b) remove the internal and external designators from the traefik service
c) test if everything still works and decide to come back to adding any of these features as we need to?

Does this sound like a plan? @jefferya & @nikathone

**Comment by nikathone** [comment]
@g7morris I am a big plus one for the proposed plan.

**Comment by jefferya** [comment]
@g7morris I like the simplicity to start and can't think of anything that  prevents a change in the future..

**Comment by jefferya** [comment]
@g7morris I like the simplicity to start and can't think of anything that  prevents a change in the future..

**Comment by g7morris** [comment]
Closing ticket as @dannylamb merged in https://github.com/Islandora-Devops/isle-dc/pull/74 . Thanks all!
